site_name: Tahapan Instalasi ELK

nav:
    - Home: 'home.md'
    - Pendahuluan: 'pendahuluan.md'
    - Instalasi:
        - 'Elasticsearch': 'elasticsearch.md'
        - 'Logstash': 'logstash.md'
        - 'Kibana': 'kibana.md'
    - Operasi: 'operasi.md'
